### ISSUE TITLE
Working Paper 게시판 개별 항목 텍스트 표시 개선 요청

### ISSUE THREAD

**Issue by YonseiFintech** [ysfintech/ysfintech#13]
![image](https://user-images.githubusercontent.com/85093457/124049350-3918cf00-da53-11eb-8a5d-ab22a3684c32.png)

![image](https://user-images.githubusercontent.com/85093457/124049117-c3acfe80-da52-11eb-91f6-259a85f89e97.png)

1. 관리자 페이지에서 enter 클릭, "\n" 입력 등의 방법을 어떻게 사용해도 게시판의 content에서 줄바꿈이 한 번 이상 되지 않습니다.
내용의 가시성을 위해 줄바꿈을 연속적으로 가능하도록 만들어주시기를 요청드립니다.

2. 또한 게시판 content 글자 크기를 조금 키워주시고 (Home 페이지의 내용 글자 크기 정도면 좋을 것 같습니다.),
내용 일부를 bold 체로 바꿀 수 있는 방법을 안내해주시면 감사하겠습니다.

확인하시면 수정 부탁드립니다.
감사합니다.

원하는 게시판 content 형태 예시
![image](https://user-images.githubusercontent.com/85093457/124050391-73836b80-da55-11eb-963c-cbd92e7c8bb9.png)
(가운데 배열은 없어도 무방합니다.)

**Comment by seunghwanly** [comment]
지원하는 에디터는 마크다운(Markdown)을 지원합니다.
마크다운은 기본적으로 왼쪽정렬이 되어있지만 정렬을 바꿀 수 있습니다.
방법은 html 태그를 사용하는 것 인데, 예를 들어서 아래와 같은 코드로 다음과 같이 나타낼 수 있습니다 :)

``` html
<p align="center">
<b>Jang, Hanwool</b><br/>
Moon Soul Graduate School of Future Strategy, KAIST
</p>
```

<p align="center">
<b>Jang, Hanwool</b><br/>
Moon Soul Graduate School of Future Strategy, KAIST
</p>

Github issue에서도 Markdown을 지원합니다 😄

**Comment by seunghwanly** [comment]
Working Paper 내 게시글 content font size 1.5배로 업데이트했습니다.
[해당 커밋 바로가기 👉](https://github.com/ysfintech/ysfintech/commit/1edcc39f0c023d602395d1df9da74e88fede08ac)
